// <auto-generated />
using System;
using Bookstore.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bookstore.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bookstore.Domain.Books.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_books");

                    b.ToTable("books", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b9b6ce9-9eb0-497b-90c7-2e5be345f139"),
                            Price = 675m,
                            Title = "Clean Architecture"
                        },
                        new
                        {
                            Id = new Guid("9e9a1fa2-9c28-4404-bcba-f81c6f70264b"),
                            Price = 590m,
                            Title = "Onion Architecture"
                        },
                        new
                        {
                            Id = new Guid("19d8fb37-087f-45a3-b261-683261249c3f"),
                            Price = 450m,
                            Title = "Vertical Slice Architecture"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
