<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Ramazan.Mediator" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bookstore.Domain\Bookstore.Domain.csproj" />
  </ItemGroup>

</Project>
