<Project>
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<AnalysisLevel>latest</AnalysisLevel>
		<AnalysisMode>default</AnalysisMode>
	</PropertyGroup>
</Project>